# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/system_mnist_0_0.xci
# IP: The module: 'system_mnist_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnW_buffer/fcnnW_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcnnW_buffer || ORIG_REF_NAME==fcnnW_buffer} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/conv2_ram/conv2_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv2_ram || ORIG_REF_NAME==conv2_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/sigmoid_blkmem/sigmoid_blkmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sigmoid_blkmem || ORIG_REF_NAME==sigmoid_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/float_fix/float_fix.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_fix || ORIG_REF_NAME==float_fix} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/float_div/float_div.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_div || ORIG_REF_NAME==float_div} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fix_float/fix_float.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fix_float || ORIG_REF_NAME==fix_float} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/pooling_ram/pooling_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pooling_ram || ORIG_REF_NAME==pooling_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/conv_ram/conv_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_ram || ORIG_REF_NAME==conv_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnb_blkmem/fcnnb_blkmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcnnb_blkmem || ORIG_REF_NAME==fcnnb_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnW_blkmem/fcnnW_blkmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcnnW_blkmem || ORIG_REF_NAME==fcnnW_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/BN_blkmem/BN_blkmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BN_blkmem || ORIG_REF_NAME==BN_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/b2_blkmem/b2_blkmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2_blkmem || ORIG_REF_NAME==b2_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/W2_blkmem/W2_blkmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2_blkmem || ORIG_REF_NAME==W2_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/b1_blkmem/b1_blkmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b1_blkmem || ORIG_REF_NAME==b1_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/W1_blkmem/W1_blkmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W1_blkmem || ORIG_REF_NAME==W1_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/classify_ram/classify_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==classify_ram || ORIG_REF_NAME==classify_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/layer1_ram/layer1_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer1_ram || ORIG_REF_NAME==layer1_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/input_ram/input_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==input_ram || ORIG_REF_NAME==input_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fifo_maxis/fifo_maxis.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_maxis || ORIG_REF_NAME==fifo_maxis} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fifo_saxis/fifo_saxis.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_saxis || ORIG_REF_NAME==fifo_saxis} -quiet] -quiet

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnW_buffer/fcnnW_buffer_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/conv2_ram/conv2_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/sigmoid_blkmem/sigmoid_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/pooling_ram/pooling_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/conv_ram/conv_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnb_blkmem/fcnnb_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnW_blkmem/fcnnW_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/BN_blkmem/BN_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/b2_blkmem/b2_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/W2_blkmem/W2_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/b1_blkmem/b1_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/W1_blkmem/W1_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/classify_ram/classify_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/layer1_ram/layer1_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/input_ram/input_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fifo_maxis/fifo_maxis.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_maxis || ORIG_REF_NAME==fifo_maxis} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fifo_saxis/fifo_saxis.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_saxis || ORIG_REF_NAME==fifo_saxis} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/system_mnist_0_0.xci
# IP: The module: 'system_mnist_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnW_buffer/fcnnW_buffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcnnW_buffer || ORIG_REF_NAME==fcnnW_buffer} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/conv2_ram/conv2_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv2_ram || ORIG_REF_NAME==conv2_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/sigmoid_blkmem/sigmoid_blkmem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sigmoid_blkmem || ORIG_REF_NAME==sigmoid_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/float_fix/float_fix.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_fix || ORIG_REF_NAME==float_fix} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/float_div/float_div.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_div || ORIG_REF_NAME==float_div} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fix_float/fix_float.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fix_float || ORIG_REF_NAME==fix_float} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/pooling_ram/pooling_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pooling_ram || ORIG_REF_NAME==pooling_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/conv_ram/conv_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==conv_ram || ORIG_REF_NAME==conv_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnb_blkmem/fcnnb_blkmem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcnnb_blkmem || ORIG_REF_NAME==fcnnb_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnW_blkmem/fcnnW_blkmem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcnnW_blkmem || ORIG_REF_NAME==fcnnW_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/BN_blkmem/BN_blkmem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BN_blkmem || ORIG_REF_NAME==BN_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/b2_blkmem/b2_blkmem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b2_blkmem || ORIG_REF_NAME==b2_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/W2_blkmem/W2_blkmem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W2_blkmem || ORIG_REF_NAME==W2_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/b1_blkmem/b1_blkmem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==b1_blkmem || ORIG_REF_NAME==b1_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/W1_blkmem/W1_blkmem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==W1_blkmem || ORIG_REF_NAME==W1_blkmem} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/classify_ram/classify_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==classify_ram || ORIG_REF_NAME==classify_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/layer1_ram/layer1_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==layer1_ram || ORIG_REF_NAME==layer1_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/input_ram/input_ram.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==input_ram || ORIG_REF_NAME==input_ram} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fifo_maxis/fifo_maxis.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_maxis || ORIG_REF_NAME==fifo_maxis} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fifo_saxis/fifo_saxis.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_saxis || ORIG_REF_NAME==fifo_saxis} -quiet] -quiet

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnW_buffer/fcnnW_buffer_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/conv2_ram/conv2_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/sigmoid_blkmem/sigmoid_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/pooling_ram/pooling_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/conv_ram/conv_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnb_blkmem/fcnnb_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnW_blkmem/fcnnW_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/BN_blkmem/BN_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/b2_blkmem/b2_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/W2_blkmem/W2_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/b1_blkmem/b1_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/W1_blkmem/W1_blkmem_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/classify_ram/classify_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/layer1_ram/layer1_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/input_ram/input_ram_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fifo_maxis/fifo_maxis.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_maxis || ORIG_REF_NAME==fifo_maxis} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fifo_saxis/fifo_saxis.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_saxis || ORIG_REF_NAME==fifo_saxis} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
