# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/self_learning/PYNQ_Z2/prjs/ov5640_mnist/ov5640_mnist.srcs/sources_1/bd/system/ip/system_red_block_mnist_0_0/system_red_block_mnist_0_0.xci
# IP: The module: 'system_red_block_mnist_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/self_learning/PYNQ_Z2/prjs/ov5640_mnist/ov5640_mnist.srcs/sources_1/bd/system/ip/system_red_block_mnist_0_0/src/test_imgrom/test_imgrom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_imgrom || ORIG_REF_NAME==test_imgrom} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/ov5640_mnist/ov5640_mnist.srcs/sources_1/bd/system/ip/system_red_block_mnist_0_0/src/mnist_image_blkmem_1/mnist_image_blkmem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_image_blkmem || ORIG_REF_NAME==mnist_image_blkmem} -quiet] -quiet

# XDC: d:/self_learning/PYNQ_Z2/prjs/ov5640_mnist/ov5640_mnist.srcs/sources_1/bd/system/ip/system_red_block_mnist_0_0/src/test_imgrom/test_imgrom_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/ov5640_mnist/ov5640_mnist.srcs/sources_1/bd/system/ip/system_red_block_mnist_0_0/src/mnist_image_blkmem_1/mnist_image_blkmem_ooc.xdc

# IP: D:/self_learning/PYNQ_Z2/prjs/ov5640_mnist/ov5640_mnist.srcs/sources_1/bd/system/ip/system_red_block_mnist_0_0/system_red_block_mnist_0_0.xci
# IP: The module: 'system_red_block_mnist_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/self_learning/PYNQ_Z2/prjs/ov5640_mnist/ov5640_mnist.srcs/sources_1/bd/system/ip/system_red_block_mnist_0_0/src/test_imgrom/test_imgrom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_imgrom || ORIG_REF_NAME==test_imgrom} -quiet] -quiet

# IP: d:/self_learning/PYNQ_Z2/prjs/ov5640_mnist/ov5640_mnist.srcs/sources_1/bd/system/ip/system_red_block_mnist_0_0/src/mnist_image_blkmem_1/mnist_image_blkmem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mnist_image_blkmem || ORIG_REF_NAME==mnist_image_blkmem} -quiet] -quiet

# XDC: d:/self_learning/PYNQ_Z2/prjs/ov5640_mnist/ov5640_mnist.srcs/sources_1/bd/system/ip/system_red_block_mnist_0_0/src/test_imgrom/test_imgrom_ooc.xdc

# XDC: d:/self_learning/PYNQ_Z2/prjs/ov5640_mnist/ov5640_mnist.srcs/sources_1/bd/system/ip/system_red_block_mnist_0_0/src/mnist_image_blkmem_1/mnist_image_blkmem_ooc.xdc
