# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.cache/wt [current_project]
set_property parent.project_path D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths d:/self_learning/PYNQ_Z2/prjs/mnist_test/repo/ip/mnist_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/repo/src/coe/W1.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/repo/src/coe/b1.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/repo/src/coe/W2.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/repo/src/coe/b2.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/repo/src/coe/batch_normalization.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/repo/src/coe/fcnn_W.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/repo/src/coe/fcnn_b.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/repo/src/coe/sigmoid.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/repo/src/coe/one.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/src/coe/sigmoid.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/src/coe/fcnn_b.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/src/coe/fcnn_W.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/src/coe/batch_normalization.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/src/coe/b2.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/src/coe/W2.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/src/coe/b1.coe
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/src/coe/W1.coe
read_verilog -library xil_defaultlib D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/hdl/system_wrapper.v
add_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_10/bd_44e3_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_11/bd_44e3_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_16/bd_44e3_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_17/bd_44e3_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_18/bd_44e3_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_19/bd_44e3_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/bd_44e3_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_22/bd_44e3_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_23/bd_44e3_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_24/bd_44e3_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/bd_44e3_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnW_buffer/fcnnW_buffer_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/conv2_ram/conv2_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/sigmoid_blkmem/sigmoid_blkmem_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/pooling_ram/pooling_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/conv_ram/conv_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnb_blkmem/fcnnb_blkmem_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fcnnW_blkmem/fcnnW_blkmem_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/BN_blkmem/BN_blkmem_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/b2_blkmem/b2_blkmem_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/W2_blkmem/W2_blkmem_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/b1_blkmem/b1_blkmem_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/W1_blkmem/W1_blkmem_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/classify_ram/classify_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/layer1_ram/layer1_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/input_ram/input_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fifo_maxis/fifo_maxis.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_mnist_0_0/src/fifo_saxis/fifo_saxis.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_axis_data_fifo_0_1/system_axis_data_fifo_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/constrs_1/new/mnist_constr.xdc
set_property used_in_implementation false [get_files D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_test.srcs/constrs_1/new/mnist_constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
