@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jul 10 23:04:36 +0800 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim mnist_process_tb_behav -key {Behavioral:sim_1:Functional:mnist_process_tb} -tclbatch mnist_process_tb.tcl -protoinst "protoinst_files/system.protoinst" -view D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_process_tb_behav.wcfg -log simulate.log"
call xsim  mnist_process_tb_behav -key {Behavioral:sim_1:Functional:mnist_process_tb} -tclbatch mnist_process_tb.tcl -protoinst "protoinst_files/system.protoinst" -view D:/self_learning/PYNQ_Z2/prjs/mnist_test/mnist_process_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
