# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/self_learning/PYNQ_Z2/prjs/ov5640_gray/ov5640_gray.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
# IP: The module: 'system_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/self_learning/PYNQ_Z2/prjs/ov5640_gray/ov5640_gray.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/self_learning/PYNQ_Z2/prjs/ov5640_gray/ov5640_gray.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/self_learning/PYNQ_Z2/prjs/ov5640_gray/ov5640_gray.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/self_learning/PYNQ_Z2/prjs/ov5640_gray/ov5640_gray.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
# IP: The module: 'system_axi_vdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/self_learning/PYNQ_Z2/prjs/ov5640_gray/ov5640_gray.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/self_learning/PYNQ_Z2/prjs/ov5640_gray/ov5640_gray.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/self_learning/PYNQ_Z2/prjs/ov5640_gray/ov5640_gray.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_vdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
