set_property SRC_FILE_INFO {cfile:D:/self_learning/PYNQ_Z2/prjs/ov5640_mnist/ov5640_mnist.srcs/constrs_1/new/hdmi_constr.xdc rfile:../../../ov5640_mnist.srcs/constrs_1/new/hdmi_constr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports vid_rst]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {vid_data[1]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {vid_data[3]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {vid_data[5]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports vid_pwd]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U19 IOSTANDARD LVCMOS33} [get_ports {vid_data[0]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {vid_data[2]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {vid_data[4]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W14 IOSTANDARD LVCMOS33} [get_ports {vid_data[7]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y14 IOSTANDARD LVCMOS33} [get_ports vid_pclk]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports vid_vsync]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports vid_iic_scl_io]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {vid_data[6]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports vid_xclk]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V12 IOSTANDARD LVCMOS33} [get_ports vid_hsync]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports vid_iic_sda_io]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets vid_pclk_IBUF]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD TMDS_33} [get_ports TMDS_0_clk_n]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD TMDS_33} [get_ports TMDS_0_clk_p]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_n[0]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_p[0]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_n[1]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_p[1]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_n[2]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_p[2]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/mnist_0/inst/mnist_process/number_o[0]} {system_i/mnist_0/inst/mnist_process/number_o[1]} {system_i/mnist_0/inst/mnist_process/number_o[2]} {system_i/mnist_0/inst/mnist_process/number_o[3]}]]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_addr_i[0]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_addr_i[1]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_addr_i[2]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_addr_i[3]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_addr_i[4]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_addr_i[5]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_addr_i[6]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_addr_i[7]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_addr_i[8]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_addr_i[9]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_addr_i[10]}]]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {system_i/red_block_mnist_0/inst/mnist_256to1pix/v_cnt[0]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/v_cnt[1]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/v_cnt[2]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/v_cnt[3]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/v_cnt[4]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/v_cnt[5]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/v_cnt[6]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/v_cnt[7]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/v_cnt[8]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/v_cnt[9]}]]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_data_norm[0]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_data_norm[1]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_data_norm[2]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_data_norm[3]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_data_norm[4]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_data_norm[5]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_data_norm[6]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_data_norm[7]}]]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[0]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[1]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[2]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[3]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[4]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[5]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[6]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[7]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[8]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[9]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[10]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[11]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[12]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[13]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[14]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[15]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[16]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[17]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[18]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[19]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[20]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[21]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[22]} {system_i/red_block_mnist_0/inst/red_block_inst/cmos_d_o[23]}]]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[0]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[1]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[2]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[3]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[4]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[5]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[6]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[7]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[8]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[9]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[10]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[11]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[12]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[13]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[14]} {system_i/red_block_mnist_0/inst/red_block_inst/h_cnt[15]}]]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {system_i/red_block_mnist_0/inst/red_block_inst/f_cnt[0]} {system_i/red_block_mnist_0/inst/red_block_inst/f_cnt[1]} {system_i/red_block_mnist_0/inst/red_block_inst/f_cnt[2]} {system_i/red_block_mnist_0/inst/red_block_inst/f_cnt[3]} {system_i/red_block_mnist_0/inst/red_block_inst/f_cnt[4]} {system_i/red_block_mnist_0/inst/red_block_inst/f_cnt[5]}]]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[0]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[1]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[2]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[3]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[4]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[5]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[6]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[7]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[8]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[9]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[10]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[11]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[12]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[13]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[14]} {system_i/red_block_mnist_0/inst/red_block_inst/v_cnt[15]}]]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {system_i/red_block_mnist_0/inst/mnist_256to1pix/h_cnt[0]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/h_cnt[1]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/h_cnt[2]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/h_cnt[3]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/h_cnt[4]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/h_cnt[5]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/h_cnt[6]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/h_cnt[7]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/h_cnt[8]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/h_cnt[9]}]]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {system_i/red_block_mnist_0/inst/mnist_256to1pix/index[0]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/index[1]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/index[2]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/index[3]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/index[4]} {system_i/red_block_mnist_0/inst/mnist_256to1pix/index[5]}]]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list system_i/red_block_mnist_0/inst/red_block_inst/cmos_href_o]]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list system_i/red_block_mnist_0/inst/red_block_inst/cmos_vsync_o]]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list system_i/red_block_mnist_0/inst/mnist_256to1pix/mnist_data_valid_norm]]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list system_i/red_block_mnist_0/inst/red_block_inst/mnist_en]]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list system_i/red_block_mnist_0/inst/red_block_inst/mnist_start]]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list system_i/mnist_0/inst/mnist_process/number_val]]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
